config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "events#index"

  get '/user', to: 'user#show'
  resources :events
  resources :event_attendees
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, foreign_key: :creator_id, class_name: 'User'
  has_many :event_attendees, foreign_key: :attended_event_id
  has_many :attendees, through: :event_attendees, source: :event_attendee

  scope :past, -> { where('date_time < ?', Date.today) }
  scope :upcoming, -> { where('date_time > ?', Date.today) }
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :event_attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, foreign_key: :creator_id, class_name: 'Event'
  has_many :event_attendees, foreign_key: :event_attendee_id
  has_many :attended_events, through: :event_attendees
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
  before_action :authenticate_user!

  def create
    event_id = event_attendee_params[:attended_event_id]
    
    attended = EventAttendee.find_by(event_attendee_params)
    if attended
      flash[:notice] = 'You are already attending this event'
      redirect_to event_path(event_id) and return
    end

    @event_attendee = current_user.event_attendees.build(event_attendee_params)
    @event_attendee.save
    redirect_to event_path(event_id)
  end

  private

  def event_attendee_params
    params.require(:event_attendee).permit(:attended_event_id, :event_attendee_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: %i[index]

  def index
    @events = Event.all.includes(:creator, :attendees)
  end

  def show
    @event = Event.includes(:attendees).find(params[:id])
    
    attendees = @event.attendees.map(&:id)
    @current_user_attending = attendees.include?(current_user.id) ? true : false
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to @event
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :location, :date_time)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!

  def show
    @created_events = current_user.created_events
    @attended_events = current_user.attended_events
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendee_helper.rb
module EventAttendeeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/_event.html.erb
<%= link_to event_path(event), :action => 'go', class: "card" do %>
    <div class="card-content">
        <h2><%= event.title %></h2>
        <div class="card-header">
            <p>Hosted by: <%= event.creator.username %></p>
            <%#<div>Invitees</div>
            <div>Attendees</div>%>
        </div>
        <div class="card-description"> <%= event.description %></div>
        <div class="card-location">
            <div><%= event.location %></div>
            <div><%= event.date_time %></div>
        </div>
    </div>
<% end %>

app/views/events/index.html.erb
<div class="events-container">
    <h2>Upcoming Events</h2>
    <div class="card-container">
        <% @events.upcoming.each do |event| %>
            <%= render event %>
        <% end %>
    </div>
</div>

<div class="events-container">
    <h2>Past Events</h2>
    <div class="card-container">
        <% @events.past.each do |event| %>
            <%= render event %>
        <% end %>    
    </div>
</div>

app/views/events/new.html.erb
<%= form_with model: @event do |form|%>
    <div class="field">
        <%= form.text_field :title, placeholder: "Title" %>
    </div>  
    <div class="field">
        <%= form.text_area :description, placeholder: "Description" %>
    </div>  
    <div class="field">
        <%= form.text_field :location, placeholder: "Location" %>
    </div>  
    <div class="field">
        <%= form.datetime_local_field :date_time %>
    </div> 
    <%= form.submit "Create Event" %>
<% end %>

app/views/events/show.html.erb
<div class="events-container">
    <h2><%= @event.title %></h2>
    <p>Host: <%= @event.creator.username %></p>
    <p>Description: <%= @event.description %></p>
    <p>Location: <%= @event.location %></p>
    <p>Date & time: <%= @event.date_time %></p>
    <% if user_signed_in? %>
        <% if @current_user_attending %>
            <% "Do Not Attend" %>
        <% else %>
            <%= link_to "Attend", event_attendees_path(event_attendee: {attended_event_id: @event.id, event_attendee_id: current_user.id}), data: {turbo_method: "post"} %>
        <% end %>
    <% else %>
        Log in to attend.
    <% end %>
    <p>Attendees (<%= @event.attendees.length %>): </p>
    <ul>
        <% if user_signed_in? %>
            <% @event.attendees.each do |attendee| %>
                <li><%= attendee.username %></li>
            <% end %>
        <% else %>
            <li>Log in to see the attendees.</li>
        <% end %>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <nav class="navbar">
      <ul>
        <li><%= link_to "PrivateEvents", root_path, class: "logo" %></li>
        <ul class="navbar-right">
          <li><%= link_to "Create Event", new_event_path, class: "nav-button"%></li>
          <% if user_signed_in? %>
            <li><%= link_to "Account", user_path, class: "nav-button" %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-button"%>
          <% else %>
            <li><%= link_to "Log In", new_user_session_path, class: "nav-button"%></li>
            <li><%= link_to "Sign Up", new_user_registration_path, class: "nav-button"%></li>
          <% end %>
        </ul>
      </ul>
    </nav>

    <% if flash[:notice] %>
      <div class="flash-notice">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:error] %>
      <div class="flash-error">
        <% flash[:error] %>
      </div>
    <% end %>
    
    <div class="main-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/user/show.html.erb
<div class="events-container">
    <h2>My Events</h2>

    <% if @created_events.length == 0 %>
        <h3>You haven't created any events yet.</h3>
    <% else%>
        <h3>Created Events</h3>
        <div class="card-container">
            <% @created_events.each do |event| %>
                <div class="card">
                    <div class="card-content">
                        <h2><%= event.title %></h2>
                        <div class="card-header">
                            <p>Hosted by: <%= event.creator.username %></p>
                            <%#<div>Invitees</div>
                            <div>Attendees</div>%>
                        </div>
                        <div class="card-description"> <%= event.description %></div>
                        <div class="card-location">
                            <div><%= event.location %></div>
                            <div><%= event.date_time %></div>
                        </div>
                    </div>
                </div>    
            <% end %>
        </div>
    <% end %>

    <% if @attended_events.length == 0 %>
        <h3>You aren't attending any events yet.</h3>
    <% else%>
        <h3>Attended Events</h3>
        <div class="card-container">
            <% @attended_events.each do |event| %>
                <div class="card">
                    <div class="card-content">
                        <h2><%= event.title %></h2>
                        <div class="card-header">
                            <p>Hosted by: <%= event.creator.username %></p>
                            <div>Invitees</div>
                            <div>Attendees</div>
                        </div>
                        <div class="card-description"> <%= event.description %></div>
                        <div class="card-location">
                            <div><%= event.location %></div>
                            <div><%= event.date_time %></div>
                        </div>
                    </div>
                </div>    
            <% end %>
        </div>
    <% end %>
</div>